project:
  type: book
  output-dir: docs

book:
  title: "Data Science for Public Policy Part II"
  author: "Aaron R. Williams"
  date: today
  chapters:
    - index.qmd
    - 01_advanced-quarto.qmd
    - 04_web-scraping.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
    number-depth: 3
    css: www/styles.css



