project:
  type: book
  output-dir: docs

book:
  title: "Data Science for Public Policy"
  author: "Aaron R. Williams, Alena Stern, and Gabe Morrison"
  date: today
  chapters:
    - index.qmd
    - part: Basics
      chapters:
        # - intro_to_r
        # - intro_to_tidyverse
        - 02_advanced-data-cleaning.qmd
        # data visualization with ggplot2
        # exploratory data analysis

    - part: Reproducible Research
      chapters: 
        # - reproducible research with Quarto
        - 01_advanced-quarto.qmd
        # - reproducible research with git 1
        # - advanced git
    - part: Programming
      chapters:
        - 03_functions.qmd
        # - r packages
        # - apis
        - 04_web-scraping.qmd
    - part: Statistics
      chapters:
        # P1 simulation and sampling??
        - 05_simulation-and-sampling.qmd
        - 07_microsimulation.qmd   
        - 08_nonparametric-1.qmd
        - 09_nonparametric-2.qmd   
        # - data imputation
    - part: Supervised Machine Learning
      chapters:
        - 10_predictive-modeling-review.qmd # + predictive modeling review
        # - supervised classification
        # - 11_ensembling.qmd - NEED pdb_small.csv
        # - 12_regularization.qmd - NEED pdb_small.csv
    - part: Unsupervised Machine Learning
      chapters:
        # - 13_interpretable-models.qmd
        # - dimension reduction
        # - cluster analysis
        - 06_advanced-unsupervised-ml.qmd 
        # - text analysis
        # - text modeling
    - part: Other Topics
        # - geospatial analysis
        # - cloud computing S3
        # - parallel programming
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
    number-depth: 3
    css: www/styles.css
