<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.3.433">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Data Science for Public Policy - 23&nbsp; Geospatial Analysis with sf</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<link href="./28_text-analysis.html" rel="next">
<link href="./27_advanced-unsupervised-ml.html" rel="prev">
<script src="site_libs/quarto-html/quarto.js"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 20,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>

  <script src="https://polyfill.io/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<link rel="stylesheet" href="www/styles.css">
</head>

<body class="nav-sidebar floating">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar,#quarto-sidebar-glass" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
      <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./30_geospatial.html">Other Topics</a></li><li class="breadcrumb-item"><a href="./30_geospatial.html"><span class="chapter-number">23</span>&nbsp; <span class="chapter-title">Geospatial Analysis with sf</span></a></li></ol></nav>
      <a class="flex-grow-1" role="button" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar,#quarto-sidebar-glass" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
      </a>
      <button type="button" class="btn quarto-search-button" aria-label="" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal sidebar-navigation floating overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="./">Data Science for Public Policy</a> 
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Welcome</span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" aria-expanded="true">
 <span class="menu-text">Basics</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./01_intro-r.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Introduction to R</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./02_tidyverse.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Introduction to the tidyverse</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./03_advanced-data-cleaning.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Advanced Data Cleaning</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./04_data-viz.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Data Visualization with ggplot2</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./05_exploratory-data-analysis.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Exploratory Data Analysis</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" aria-expanded="true">
 <span class="menu-text">Reproducible Research</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-2" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./06_reproducible-research-with-quarto.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Reproducible Research with Quarto</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./07_advanced-quarto.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Advanced Quarto</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./08_reproducible-research-with-git.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">Reproducible Research with Git and GitHub</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./09_advanced-git.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">Advanced Git and Github</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" aria-expanded="true">
 <span class="menu-text">Programming</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-3" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./10_functions.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">10</span>&nbsp; <span class="chapter-title">Advanced R Programming</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./12_apis.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">11</span>&nbsp; <span class="chapter-title">Web Application Programming Interfaces (Web APIs)</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./13_web-scraping.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">12</span>&nbsp; <span class="chapter-title">Web Scraping</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" aria-expanded="true">
 <span class="menu-text">Statistics</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-4" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./14_simulation-and-sampling.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">13</span>&nbsp; <span class="chapter-title">Simulation and Sampling</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./15_microsimulation.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">14</span>&nbsp; <span class="chapter-title">Microsimulation</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./16_nonparametric-1.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">15</span>&nbsp; <span class="chapter-title">Nonparametric Curve Fitting</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./17_nonparametric-2.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">16</span>&nbsp; <span class="chapter-title">Nonparametric Inference</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-5" aria-expanded="true">
 <span class="menu-text">Supervised Machine Learning</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-5" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-5" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./19_predictive-modeling-motivation.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">17</span>&nbsp; <span class="chapter-title">Predictive Modeling Motivation</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./20_predictive-modeling-concepts.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">18</span>&nbsp; <span class="chapter-title">Predictive Modeling Concepts and Regression</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./21_supervised-classification.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">19</span>&nbsp; <span class="chapter-title">Classification</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./22_ensembling.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">20</span>&nbsp; <span class="chapter-title">Ensembling</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./23_regularization.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">21</span>&nbsp; <span class="chapter-title">Regularization</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-6" aria-expanded="true">
 <span class="menu-text">Unsupervised Machine Learning</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-6" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-6" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./27_advanced-unsupervised-ml.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">22</span>&nbsp; <span class="chapter-title">Mixture Distributions and Mixture Modeling</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-7" aria-expanded="true">
 <span class="menu-text">Other Topics</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-7" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-7" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./30_geospatial.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text"><span class="chapter-number">23</span>&nbsp; <span class="chapter-title">Geospatial Analysis with sf</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./28_text-analysis.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">24</span>&nbsp; <span class="chapter-title">Text Analysis</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./29_text-modeling.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">25</span>&nbsp; <span class="chapter-title">Text Modeling</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./references.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">References</span></a>
  </div>
</li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar,#quarto-sidebar-glass"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#motivation" id="toc-motivation" class="nav-link active" data-scroll-target="#motivation"><span class="header-section-number">23.1</span> Motivation</a></li>
  <li><a href="#librarysf-and-geospatial-data" id="toc-librarysf-and-geospatial-data" class="nav-link" data-scroll-target="#librarysf-and-geospatial-data"><span class="header-section-number">23.2</span> <code>library(sf)</code> and geospatial data</a>
  <ul class="collapse">
  <li><a href="#points" id="toc-points" class="nav-link" data-scroll-target="#points"><span class="header-section-number">23.2.1</span> Points</a></li>
  <li><a href="#linestrings" id="toc-linestrings" class="nav-link" data-scroll-target="#linestrings"><span class="header-section-number">23.2.2</span> Linestrings</a></li>
  <li><a href="#polygons" id="toc-polygons" class="nav-link" data-scroll-target="#polygons"><span class="header-section-number">23.2.3</span> Polygons</a></li>
  <li><a href="#multi-geometries" id="toc-multi-geometries" class="nav-link" data-scroll-target="#multi-geometries"><span class="header-section-number">23.2.4</span> Multi-Geometries</a></li>
  </ul></li>
  <li><a href="#geom_sf" id="toc-geom_sf" class="nav-link" data-scroll-target="#geom_sf"><span class="header-section-number">23.3</span> <code>geom_sf()</code></a></li>
  <li><a href="#getting-and-loading-spatial-data" id="toc-getting-and-loading-spatial-data" class="nav-link" data-scroll-target="#getting-and-loading-spatial-data"><span class="header-section-number">23.4</span> Getting and loading spatial data</a>
  <ul class="collapse">
  <li><a href="#shapefiles" id="toc-shapefiles" class="nav-link" data-scroll-target="#shapefiles"><span class="header-section-number">23.4.1</span> Shapefiles</a></li>
  <li><a href="#geojson" id="toc-geojson" class="nav-link" data-scroll-target="#geojson"><span class="header-section-number">23.4.2</span> GeoJSON</a></li>
  <li><a href="#csv-files" id="toc-csv-files" class="nav-link" data-scroll-target="#csv-files"><span class="header-section-number">23.4.3</span> .csv files</a></li>
  <li><a href="#librarytigris" id="toc-librarytigris" class="nav-link" data-scroll-target="#librarytigris"><span class="header-section-number">23.4.4</span> <code>library(tigris)</code></a></li>
  <li><a href="#librarytidycensus" id="toc-librarytidycensus" class="nav-link" data-scroll-target="#librarytidycensus"><span class="header-section-number">23.4.5</span> <code>library(tidycensus)</code></a></li>
  </ul></li>
  <li><a href="#choropleths" id="toc-choropleths" class="nav-link" data-scroll-target="#choropleths"><span class="header-section-number">23.5</span> Choropleths</a></li>
  <li><a href="#spatial-concepts" id="toc-spatial-concepts" class="nav-link" data-scroll-target="#spatial-concepts"><span class="header-section-number">23.6</span> Spatial concepts</a>
  <ul class="collapse">
  <li><a href="#popular-projections" id="toc-popular-projections" class="nav-link" data-scroll-target="#popular-projections"><span class="header-section-number">23.6.1</span> Popular projections</a></li>
  </ul></li>
  <li><a href="#spatial-operations" id="toc-spatial-operations" class="nav-link" data-scroll-target="#spatial-operations"><span class="header-section-number">23.7</span> Spatial operations</a>
  <ul class="collapse">
  <li><a href="#aggregation" id="toc-aggregation" class="nav-link" data-scroll-target="#aggregation"><span class="header-section-number">23.7.1</span> Aggregation</a></li>
  <li><a href="#spatial-joins" id="toc-spatial-joins" class="nav-link" data-scroll-target="#spatial-joins"><span class="header-section-number">23.7.2</span> Spatial Joins</a></li>
  <li><a href="#buffers" id="toc-buffers" class="nav-link" data-scroll-target="#buffers"><span class="header-section-number">23.7.3</span> Buffers</a></li>
  <li><a href="#distances" id="toc-distances" class="nav-link" data-scroll-target="#distances"><span class="header-section-number">23.7.4</span> Distances</a></li>
  </ul></li>
  <li><a href="#geospatial-modeling" id="toc-geospatial-modeling" class="nav-link" data-scroll-target="#geospatial-modeling"><span class="header-section-number">23.8</span> Geospatial modeling</a></li>
  <li><a href="#parting-thoughts" id="toc-parting-thoughts" class="nav-link" data-scroll-target="#parting-thoughts"><span class="header-section-number">23.9</span> Parting Thoughts</a></li>
  <li><a href="#more-resources" id="toc-more-resources" class="nav-link" data-scroll-target="#more-resources"><span class="header-section-number">23.10</span> More Resources</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title"><span class="chapter-number">23</span>&nbsp; <span class="chapter-title">Geospatial Analysis with sf</span></h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  
<div>
  <div class="abstract">
    <div class="abstract-title">Abstract</div>
    In this chapter, we introduce mapping and geospatial analysis using the simple features framework in R.
  </div>
</div>

</header>

<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="images/header-images/Tabula_Rogeriana_1929_copy_by_Konrad_Miller.jpg" class="img-fluid figure-img"></p>
<figcaption class="figure-caption">The Tabula Rogeriana was an early world atlas by geographer Al Idrisi. This is a reconstituion by Konrad Miller.</figcaption>
</figure>
</div>
<section id="motivation" class="level2" data-number="23.1">
<h2 data-number="23.1" class="anchored" data-anchor-id="motivation"><span class="header-section-number">23.1</span> Motivation</h2>
<ul>
<li>Many data are inherently spatial. We need tools to manipulate, explore, communicate, and model spatial data.</li>
<li>Point-and-click tools suffer many of the drawbacks outlined in earlier note sets.</li>
<li>Proprietary geospatial tools are prohibitively expensive.</li>
<li>Everyone loves maps.</li>
</ul>
</section>
<section id="librarysf-and-geospatial-data" class="level2" data-number="23.2">
<h2 data-number="23.2" class="anchored" data-anchor-id="librarysf-and-geospatial-data"><span class="header-section-number">23.2</span> <code>library(sf)</code> and geospatial data</h2>
<p>Geospatial data are multidimensional. The outline of a simple rectangular state like Kansas may have a few vertices and a complex state like West Virginia may have many more vertices. Furthermore, geospatial data have auxiliary information about bounding boxes and projections. Fortunately, <code>library(sf)</code> can store all of this information in a rectangular tibble that works well with <code>library(dplyr)</code> and <code>library(ggplot2)</code>.</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Note
</div>
</div>
<div class="callout-body-container callout-body">
<p>If you are looking online, you may notice R code written in the (similarly named) <code>library(sp)</code> package. <code>library(sp)</code> is older than <code>library(sf)</code>, and <code>library(sp)</code> <a href="https://geocompx.org/post/2023/rgdal-retirement/">is no longer being developed</a>. Among its many advantages, <code>library(sf)</code> integrates seamlessly with the tidyverse.</p>
</div>
</div>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Simple features
</div>
</div>
<div class="callout-body-container callout-body">
<p>Simple features is a standard for storing and accessing geometric features outlined in the ISO 19125 standard.</p>
</div>
</div>
<p><code>library(sf)</code> stores data in a sf dataframe. sf dataframes are similar to normal dataframes except that, in addition to regular rows and columns, they have a special <code>geometry</code> column that stores vector geospatial data. You can think of each record in an sf dataframe as having two sets of data: 1. <strong>Attribute data</strong>: the non-spatial data. These data are stored in all columns except the <code>geometry</code> column 2. <strong>Geographic data</strong>: the geospatial data stored in the <code>geometry</code> column.</p>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Vector Geospatial data
</div>
</div>
<div class="callout-body-container callout-body">
<p>Vector geospatial data consist of some combination of <strong>points</strong>, <strong>lines</strong>, or <strong>polygons</strong>.</p>
</div>
</div>
<p>Consider this example of vector geospatial data:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1"></a><span class="fu">library</span>(sf)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Linking to GEOS 3.11.0, GDAL 3.5.3, PROJ 9.1.0; sf_use_s2() is TRUE</code></pre>
</div>
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1"></a>amtrak_stations_file <span class="ot">&lt;-</span> </span>
<span id="cb3-2"><a href="#cb3-2"></a>  <span class="fu">here</span>(<span class="st">"data"</span>, <span class="st">"amtrak_stations.geojson"</span>)</span>
<span id="cb3-3"><a href="#cb3-3"></a></span>
<span id="cb3-4"><a href="#cb3-4"></a><span class="co"># download Amtrak data</span></span>
<span id="cb3-5"><a href="#cb3-5"></a><span class="cf">if</span>(<span class="sc">!</span><span class="fu">file.exists</span>(amtrak_stations_file)) {</span>
<span id="cb3-6"><a href="#cb3-6"></a>  </span>
<span id="cb3-7"><a href="#cb3-7"></a>  <span class="fu">download.file</span>(</span>
<span id="cb3-8"><a href="#cb3-8"></a>    <span class="at">url =</span> <span class="st">"https://opendata.arcgis.com/datasets/628537f4cf774cde8aa9721212226390_0.geojson"</span>,</span>
<span id="cb3-9"><a href="#cb3-9"></a>    <span class="at">destfile =</span> amtrak_stations_file</span>
<span id="cb3-10"><a href="#cb3-10"></a>  )</span>
<span id="cb3-11"><a href="#cb3-11"></a>  </span>
<span id="cb3-12"><a href="#cb3-12"></a>}</span>
<span id="cb3-13"><a href="#cb3-13"></a></span>
<span id="cb3-14"><a href="#cb3-14"></a><span class="co"># read sf data</span></span>
<span id="cb3-15"><a href="#cb3-15"></a>amtrak_stations <span class="ot">&lt;-</span> <span class="fu">st_read</span>(amtrak_stations_file, <span class="at">quiet =</span> <span class="cn">TRUE</span>)</span>
<span id="cb3-16"><a href="#cb3-16"></a></span>
<span id="cb3-17"><a href="#cb3-17"></a><span class="co"># print the geometry column</span></span>
<span id="cb3-18"><a href="#cb3-18"></a><span class="co"># </span><span class="al">NOTE</span><span class="co">: geometry columns are "sticky" -- geometry is returned even though it </span></span>
<span id="cb3-19"><a href="#cb3-19"></a><span class="co"># isn't include in select()</span></span>
<span id="cb3-20"><a href="#cb3-20"></a>amtrak_stations <span class="sc">|&gt;</span></span>
<span id="cb3-21"><a href="#cb3-21"></a>  <span class="fu">select</span>(stationnam)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Simple feature collection with 1096 features and 1 field
Geometry type: POINT
Dimension:     XY
Bounding box:  xmin: -124.2883 ymin: 25.84956 xmax: -68.67001 ymax: 49.27376
Geodetic CRS:  WGS 84
First 10 features:
              stationnam                   geometry
1               Alma, MI POINT (-84.64484 43.39173)
2             Albany, NY  POINT (-73.80919 42.7445)
3   Abbotsford-Colby, WI POINT (-90.31467 44.92856)
4           Aberdeen, MD POINT (-76.16326 39.50845)
5            Absecon, NJ POINT (-74.50148 39.42405)
6        Albuquerque, NM  POINT (-106.648 35.08207)
7  Antioch-Pittsburg, CA  POINT (-121.816 38.01771)
8            Arcadia, MO POINT (-90.62441 37.59217)
9      Atlantic City, NJ   POINT (-74.4399 39.3627)
10           Ardmore, OK POINT (-97.12552 34.17247)</code></pre>
</div>
</div>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Note
</div>
</div>
<div class="callout-body-container callout-body">
<p>The geometry column in a <code>sf</code> dataframe is “sticky.” Even though <code>geometry</code> was not included in <code>select()</code>, it is still returned. <code>sf</code> works this way because the spatial data stored in the geometry column is essential to the object (it couldn’t be a geospatial data set without the geographic component of the data!).</p>
<p>If you are dead-set on dropping a geometry column, you can use <code>sf::st_drop_geometry()</code> which returns a data.frame.</p>
</div>
</div>
<section id="points" class="level3" data-number="23.2.1">
<h3 data-number="23.2.1" class="anchored" data-anchor-id="points"><span class="header-section-number">23.2.1</span> Points</h3>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Points
</div>
</div>
<div class="callout-body-container callout-body">
<p>Points, which <code>library(sf)</code> calls <code>POINT</code>, are zero-dimensional geospatial objects. Points are often a single longitude and latitude.</p>
</div>
</div>
<p>Let’s map the Amtrak stations from the above example:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1"></a><span class="co"># create a map</span></span>
<span id="cb5-2"><a href="#cb5-2"></a>amtrak_stations <span class="sc">|&gt;</span></span>
<span id="cb5-3"><a href="#cb5-3"></a>  <span class="fu">ggplot</span>() <span class="sc">+</span></span>
<span id="cb5-4"><a href="#cb5-4"></a>  <span class="fu">geom_sf</span>() <span class="sc">+</span></span>
<span id="cb5-5"><a href="#cb5-5"></a>  <span class="fu">labs</span>(</span>
<span id="cb5-6"><a href="#cb5-6"></a>    <span class="at">title =</span> <span class="st">"Example of point data"</span>,</span>
<span id="cb5-7"><a href="#cb5-7"></a>    <span class="at">caption =</span> <span class="st">"Amtrak stations from opendata.arcgis.com"</span>) <span class="sc">+</span></span>
<span id="cb5-8"><a href="#cb5-8"></a>  <span class="fu">theme_void</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="30_geospatial_files/figure-html/unnamed-chunk-4-1.png" class="img-fluid" width="672"></p>
</div>
</div>
</section>
<section id="linestrings" class="level3" data-number="23.2.2">
<h3 data-number="23.2.2" class="anchored" data-anchor-id="linestrings"><span class="header-section-number">23.2.2</span> Linestrings</h3>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Linestrings
</div>
</div>
<div class="callout-body-container callout-body">
<p>A line (<code>LINESTRING</code>) is composed of a sequence of multiple points.</p>
</div>
</div>
<p>Here is an example of Amtrak train routes from the <a href="https://data-usdot.opendata.arcgis.com/">Bureau of Transportation Statistics</a>:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1"></a>amtrak_routes_file <span class="ot">&lt;-</span> <span class="fu">here</span>(<span class="st">"data"</span>, <span class="st">"Amtrak_Routes.geojson"</span>)</span>
<span id="cb6-2"><a href="#cb6-2"></a></span>
<span id="cb6-3"><a href="#cb6-3"></a><span class="co"># load sf data</span></span>
<span id="cb6-4"><a href="#cb6-4"></a>amtrak_routes <span class="ot">&lt;-</span> <span class="fu">st_read</span>(amtrak_routes_file, <span class="at">quiet =</span> <span class="cn">TRUE</span>)</span>
<span id="cb6-5"><a href="#cb6-5"></a></span>
<span id="cb6-6"><a href="#cb6-6"></a><span class="co"># create map with lines data</span></span>
<span id="cb6-7"><a href="#cb6-7"></a>amtrak_routes <span class="sc">|&gt;</span></span>
<span id="cb6-8"><a href="#cb6-8"></a>  <span class="fu">ggplot</span>() <span class="sc">+</span></span>
<span id="cb6-9"><a href="#cb6-9"></a>  <span class="fu">geom_sf</span>() <span class="sc">+</span></span>
<span id="cb6-10"><a href="#cb6-10"></a>  <span class="fu">labs</span>(</span>
<span id="cb6-11"><a href="#cb6-11"></a>    <span class="at">title =</span> <span class="st">"Example of line data"</span>,</span>
<span id="cb6-12"><a href="#cb6-12"></a>    <span class="at">caption =</span> <span class="st">"Amtrak routes from Bureau of Transportation Statistics"</span></span>
<span id="cb6-13"><a href="#cb6-13"></a>  ) <span class="sc">+</span></span>
<span id="cb6-14"><a href="#cb6-14"></a>  <span class="fu">theme_void</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="30_geospatial_files/figure-html/unnamed-chunk-5-1.png" class="img-fluid" width="672"></p>
</div>
</div>
</section>
<section id="polygons" class="level3" data-number="23.2.3">
<h3 data-number="23.2.3" class="anchored" data-anchor-id="polygons"><span class="header-section-number">23.2.3</span> Polygons</h3>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Polygons
</div>
</div>
<div class="callout-body-container callout-body">
<p>Polygons (<code>POLYGON</code>) are two-dimensional geospatial objects. Like lines, polygons are composed of many points, but the first and last point in a polygon must be the same.</p>
</div>
</div>
<p>Here is a simple example with of the Continental United States:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1"></a><span class="co"># load and subset states data</span></span>
<span id="cb7-2"><a href="#cb7-2"></a>states <span class="ot">&lt;-</span> tigris<span class="sc">::</span><span class="fu">states</span>(<span class="at">cb =</span> <span class="cn">TRUE</span>, <span class="at">progress_bar =</span> <span class="cn">FALSE</span>) <span class="sc">|&gt;</span></span>
<span id="cb7-3"><a href="#cb7-3"></a>  <span class="fu">filter</span>(<span class="sc">!</span>STATEFP <span class="sc">%in%</span> <span class="fu">c</span>(<span class="st">"78"</span>, <span class="st">"69"</span>, <span class="st">"66"</span>, <span class="st">"60"</span>, <span class="st">"72"</span>, <span class="st">"02"</span>, <span class="st">"15"</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Retrieving data for the year 2021</code></pre>
</div>
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1"></a>states <span class="sc">|&gt;</span></span>
<span id="cb9-2"><a href="#cb9-2"></a>  <span class="fu">ggplot</span>() <span class="sc">+</span></span>
<span id="cb9-3"><a href="#cb9-3"></a>  <span class="fu">geom_sf</span>() <span class="sc">+</span></span>
<span id="cb9-4"><a href="#cb9-4"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Example of polygon data"</span>) <span class="sc">+</span></span>
<span id="cb9-5"><a href="#cb9-5"></a>  <span class="fu">theme_void</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="30_geospatial_files/figure-html/unnamed-chunk-6-1.png" class="img-fluid" width="672"></p>
</div>
</div>
</section>
<section id="multi-geometries" class="level3" data-number="23.2.4">
<h3 data-number="23.2.4" class="anchored" data-anchor-id="multi-geometries"><span class="header-section-number">23.2.4</span> Multi-Geometries</h3>
<p>In practice, many records in a sf dataframe do not have type <code>LINE</code>, <code>POINT</code> or <code>POLYGON</code>, but rather have type <code>MULTIPOINT</code>, <code>MULTILINE</code> or <code>MULTIPOLYGON</code>. This means that, for any given record in a sf dataframe, the non-spatial data is associated with multiple points, lines, or polygons, respectively.</p>
<p>Consider the example of California. California is a single state, so, in the <code>states</code> sf dataframe above, it should be a single record. However, California has not only one large landmass but also many small islands, each of which is its own polygon. Given that California is composed of multiple polygons, the <code>MULTIPOLYGON</code> type is most well-suited for representing it.</p>
<p><code>library(sf)</code> can represent 18 geometry types. To read about the 12 we do not mention, read the <a href="https://r-spatial.github.io/sf/articles/sf1.html">sf documentation</a>.</p>
<p>If you are struggling with these concepts or want to read about them in greater depth, see <a href="https://r.geocompx.org/spatial-class#geometry">Chapter 2.2.4</a> of <em>Geocomputation with R</em>.</p>
<p><code>library(sf)</code> implements simple features in R and introduces <code>sf</code> data.</p>
</section>
</section>
<section id="geom_sf" class="level2" data-number="23.3">
<h2 data-number="23.3" class="anchored" data-anchor-id="geom_sf"><span class="header-section-number">23.3</span> <code>geom_sf()</code></h2>
<p><code>geom_sf()</code> plots <code>sf</code> data. The function automatically references the <code>geometry</code> column and does not require any aesthetic mappings. <code>geom_sf()</code> works well with layers and it is simple to combine point, line, and polygon data.</p>
<p><code>geom_sf()</code> works like <code>geom_point()</code> for point data, <code>geom_line()</code> for linestring data, and <code>geom_area()</code> for polygon data (e.g.&nbsp;the <code>fill</code> argument controls the color of shapes and color controls the border colors of shapes for polygons).</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1"></a>amtrak_map <span class="ot">&lt;-</span> <span class="fu">ggplot</span>() <span class="sc">+</span></span>
<span id="cb10-2"><a href="#cb10-2"></a>  <span class="fu">geom_sf</span>(</span>
<span id="cb10-3"><a href="#cb10-3"></a>    <span class="at">data =</span> states,</span>
<span id="cb10-4"><a href="#cb10-4"></a>    <span class="at">fill =</span> <span class="cn">NA</span></span>
<span id="cb10-5"><a href="#cb10-5"></a>  ) <span class="sc">+</span></span>
<span id="cb10-6"><a href="#cb10-6"></a>  <span class="fu">geom_sf</span>(</span>
<span id="cb10-7"><a href="#cb10-7"></a>    <span class="at">data =</span> amtrak_routes, </span>
<span id="cb10-8"><a href="#cb10-8"></a>    <span class="at">color =</span> <span class="st">"blue"</span></span>
<span id="cb10-9"><a href="#cb10-9"></a>  ) <span class="sc">+</span></span>
<span id="cb10-10"><a href="#cb10-10"></a>  <span class="fu">geom_sf</span>(</span>
<span id="cb10-11"><a href="#cb10-11"></a>    <span class="at">data =</span> amtrak_stations, </span>
<span id="cb10-12"><a href="#cb10-12"></a>    <span class="at">color =</span> <span class="st">"red"</span>, </span>
<span id="cb10-13"><a href="#cb10-13"></a>    <span class="at">size =</span> <span class="fl">0.75</span>,</span>
<span id="cb10-14"><a href="#cb10-14"></a>    <span class="at">alpha =</span> <span class="fl">0.5</span></span>
<span id="cb10-15"><a href="#cb10-15"></a>  ) <span class="sc">+</span></span>
<span id="cb10-16"><a href="#cb10-16"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Amtrak stations and train routes"</span>) <span class="sc">+</span></span>
<span id="cb10-17"><a href="#cb10-17"></a>  <span class="fu">theme_void</span>()</span>
<span id="cb10-18"><a href="#cb10-18"></a></span>
<span id="cb10-19"><a href="#cb10-19"></a>amtrak_map</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="30_geospatial_files/figure-html/unnamed-chunk-7-1.png" class="img-fluid" width="672"></p>
</div>
</div>
</section>
<section id="getting-and-loading-spatial-data" class="level2" data-number="23.4">
<h2 data-number="23.4" class="anchored" data-anchor-id="getting-and-loading-spatial-data"><span class="header-section-number">23.4</span> Getting and loading spatial data</h2>
<section id="shapefiles" class="level3" data-number="23.4.1">
<h3 data-number="23.4.1" class="anchored" data-anchor-id="shapefiles"><span class="header-section-number">23.4.1</span> Shapefiles</h3>
<p>Shapefiles are a proprietary file format created by ESRI, the company that creates ArcGIS. Shapefiles are popular because ESRI dominated the GIS space for a long time. A shapefile is actually usually three or more binary files.</p>
<p><code>st_read()</code> reads shapefiles into R in the <code>sf</code> format. Simply point the function to the file ending in <code>.shp</code>.</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Note
</div>
</div>
<div class="callout-body-container callout-body">
<p>Note that the other binary files associated with the shapefile must also be located in the same directory as the <code>.shp</code> file.</p>
</div>
</div>
</section>
<section id="geojson" class="level3" data-number="23.4.2">
<h3 data-number="23.4.2" class="anchored" data-anchor-id="geojson"><span class="header-section-number">23.4.2</span> GeoJSON</h3>
<p>.geojson is an open source file type for storing geospatial data. It is plain text, which means it plays well with version control.</p>
<p><code>st_read()</code> also reads GeoJSON data. Point the function at a file ending in .geojson to read the data.</p>
</section>
<section id="csv-files" class="level3" data-number="23.4.3">
<h3 data-number="23.4.3" class="anchored" data-anchor-id="csv-files"><span class="header-section-number">23.4.3</span> .csv files</h3>
<p>Lots of geographic information is stored in .csv files–especially for point data where it is sensible to have a longitude and latitude columns. Loading point data from .csv files requires two steps. First, read the file with <code>read_csv()</code>. Second, use <code>st_as_sf()</code> to convert the tibble into an sf object and specify the columns with longitude and latitude with the <code>coords</code> argument:</p>
<div class="sourceCode" id="cb11"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1"></a><span class="fu">st_as_sf</span>(data, <span class="at">coords =</span> <span class="fu">c</span>(<span class="st">"lon"</span>, <span class="st">"lat"</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Note
</div>
</div>
<div class="callout-body-container callout-body">
<p>It is trickier (but far less common) to load line, polygon, and multipolygon data from <code>.csvs</code>.</p>
</div>
</div>
</section>
<section id="librarytigris" class="level3" data-number="23.4.4">
<h3 data-number="23.4.4" class="anchored" data-anchor-id="librarytigris"><span class="header-section-number">23.4.4</span> <code>library(tigris)</code></h3>
<p><a href="https://github.com/walkerke/tigris"><code>library(tigris)</code></a> is an exceptional package that downloads and provides TIGER/Line shapefiles from the US Census Bureau. TIGER stands for Topologically Integrated Geographic Encoding and Referencing.</p>
<p>The package provides lots of data with simple functions (<a href="https://github.com/walkerke/tigris">full list here</a>) like <code>counties()</code> to access counties, <code>tracts()</code> to access census tracts, and <code>roads()</code> to access roads. The <code>state</code> and <code>county</code> arguments accept names and FIPS codes.</p>
<p><code>library(tigris)</code> has a new <code>shift</code> option that elides Alaska and Hawaii next to the Continental United States.</p>
<div class="callout callout-style-simple callout-none no-icon callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span style="color:#1696d2;">Exercise 1</span>
</div>
</div>
<div class="callout-body-container callout-body">
<ol type="1">
<li>Using <code>library(tigris)</code>, pull roads data for DC with <code>state = "DC"</code> and <code>county = "District of Columbia"</code>.</li>
<li>Create a map with <code>geom_sf()</code> and <code>theme_void()</code>.</li>
</ol>
</div>
</div>
<p>TIGER line files are high-resolution and follow legal boundaries. Sometimes the maps are counterintuitive. For example, the outline of Michigan will include the Great Lakes, which is uncommon. Cartographic boundary files are quicker to download and are clipped to the coastline, which better aligns with expectations.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1"></a><span class="fu">library</span>(tigris)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>To enable caching of data, set `options(tigris_use_cache = TRUE)`
in your R script or .Rprofile.</code></pre>
</div>
<div class="sourceCode cell-code" id="cb14"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1"></a><span class="fu">library</span>(patchwork)</span>
<span id="cb14-2"><a href="#cb14-2"></a></span>
<span id="cb14-3"><a href="#cb14-3"></a>mi <span class="ot">&lt;-</span> <span class="fu">states</span>(<span class="at">progress_bar =</span> <span class="cn">FALSE</span>) <span class="sc">|&gt;</span></span>
<span id="cb14-4"><a href="#cb14-4"></a>  <span class="fu">filter</span>(STUSPS <span class="sc">==</span> <span class="st">"MI"</span>) <span class="sc">|&gt;</span></span>
<span id="cb14-5"><a href="#cb14-5"></a>  <span class="fu">ggplot</span>() <span class="sc">+</span></span>
<span id="cb14-6"><a href="#cb14-6"></a>  <span class="fu">geom_sf</span>() <span class="sc">+</span></span>
<span id="cb14-7"><a href="#cb14-7"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"TIGER/Line"</span>) <span class="sc">+</span></span>
<span id="cb14-8"><a href="#cb14-8"></a>  <span class="fu">theme_void</span>() </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Retrieving data for the year 2021</code></pre>
</div>
<div class="sourceCode cell-code" id="cb16"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1"></a>mi_cb <span class="ot">&lt;-</span> <span class="fu">states</span>(<span class="at">cb =</span> <span class="cn">TRUE</span>, <span class="at">progress_bar =</span> <span class="cn">FALSE</span>) <span class="sc">|&gt;</span></span>
<span id="cb16-2"><a href="#cb16-2"></a>  <span class="fu">filter</span>(STUSPS <span class="sc">==</span> <span class="st">"MI"</span>) <span class="sc">|&gt;</span></span>
<span id="cb16-3"><a href="#cb16-3"></a>  <span class="fu">ggplot</span>() <span class="sc">+</span></span>
<span id="cb16-4"><a href="#cb16-4"></a>  <span class="fu">geom_sf</span>() <span class="sc">+</span></span>
<span id="cb16-5"><a href="#cb16-5"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Cartographic Boundary"</span>) <span class="sc">+</span>  </span>
<span id="cb16-6"><a href="#cb16-6"></a>  <span class="fu">theme_void</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Retrieving data for the year 2021</code></pre>
</div>
<div class="sourceCode cell-code" id="cb18"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1"></a>mi <span class="sc">+</span> mi_cb</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="30_geospatial_files/figure-html/unnamed-chunk-10-1.png" class="img-fluid" width="384"></p>
</div>
</div>
<p><code>library(rgeoboundaries)</code></p>
<p>The <a href="https://rspatialdata.github.io/admin_boundaries.html"><code>rgeoboundaries</code></a> package is a client for the <a href="https://www.geoboundaries.org/">geoBoundaries API</a>, providing country political administrative boundaries for countries around the world. This package can be installed from GitHub using the <code>remotes</code> package as follows</p>
<p>The <code>rgeoboundaries</code> package can provide boundaries for countries at different administrative division levels. For example, here we obtain the adm1 boundaries (the first subnational level) for Bangladesh. The <code>type</code> argument of the <code>geoboundaries()</code> function can be set to obtain a simplified version of the boundaries.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb19"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1"></a><span class="fu">library</span>(rgeoboundaries)</span>
<span id="cb19-2"><a href="#cb19-2"></a></span>
<span id="cb19-3"><a href="#cb19-3"></a>bangladesh <span class="ot">&lt;-</span> <span class="fu">geoboundaries</span>(</span>
<span id="cb19-4"><a href="#cb19-4"></a>  <span class="at">country =</span> <span class="st">"Bangladesh"</span>, </span>
<span id="cb19-5"><a href="#cb19-5"></a>  <span class="at">adm_lvl =</span> <span class="st">"adm1"</span>,</span>
<span id="cb19-6"><a href="#cb19-6"></a>  <span class="at">type =</span> <span class="st">"SSCGS"</span> <span class="co"># Simplified Single Country Globally Standardized</span></span>
<span id="cb19-7"><a href="#cb19-7"></a>) </span>
<span id="cb19-8"><a href="#cb19-8"></a></span>
<span id="cb19-9"><a href="#cb19-9"></a><span class="fu">ggplot</span>(<span class="at">data =</span> bangladesh) <span class="sc">+</span></span>
<span id="cb19-10"><a href="#cb19-10"></a>  <span class="fu">geom_sf</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="30_geospatial_files/figure-html/unnamed-chunk-11-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<div class="callout callout-style-simple callout-none no-icon callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span style="color:#1696d2;">Exercise 2</span>
</div>
</div>
<div class="callout-body-container callout-body">
<p>We want to read in and map the locations of World Bank development projects in Bangladesh downloaded from <a href="https://www.aiddata.org/data/world-bank-geocoded-research-release-level-1-v1-4-2">AidData</a>, which includes geographic and other information about development projects.</p>
<ol type="1">
<li>Copy the below code into your script to read in <code>aiddata_bangladesh.csv</code> with read_csv().</li>
</ol>
<div class="cell">
<div class="sourceCode cell-code" id="cb20"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1"></a>aiddata <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(</span>
<span id="cb20-2"><a href="#cb20-2"></a>  <span class="fu">paste0</span>(</span>
<span id="cb20-3"><a href="#cb20-3"></a>    <span class="st">"https://raw.githubusercontent.com/awunderground/awunderground-data/"</span>,</span>
<span id="cb20-4"><a href="#cb20-4"></a>    <span class="st">"main/aiddata/aiddata_bangladesh.csv"</span></span>
<span id="cb20-5"><a href="#cb20-5"></a>    )</span>
<span id="cb20-6"><a href="#cb20-6"></a>  )</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Rows: 2648 Columns: 21
── Column specification ────────────────────────────────────────────────────────
Delimiter: ","
chr (15): project_id, project_location_id, place_name, location_type_code, l...
dbl  (6): precision_code, geoname_id, latitude, longitude, location_class, g...

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.</code></pre>
</div>
</div>
<ol start="2" type="1">
<li>Use <code>st_as_sf()</code> to convert the .csv to <code>sf</code>.</li>
<li>Use <code>st_set_crs(value = 4326)</code> to set the CRS (we will discuss below).</li>
<li>Add a basemap of adm1 boundaries for Bangladesh using the <code>bangladesh</code> object created above.</li>
<li>Map the Bangladesh development project data with <code>color = status</code>.</li>
</ol>
</div>
</div>
</section>
<section id="librarytidycensus" class="level3" data-number="23.4.5">
<h3 data-number="23.4.5" class="anchored" data-anchor-id="librarytidycensus"><span class="header-section-number">23.4.5</span> <code>library(tidycensus)</code></h3>
<p><a href="https://walker-data.com/tidycensus/articles/spatial-data.html"><code>library(tidycensus)</code></a>, which was created by the creator of <code>library(tigris)</code>, is also a valuable source of geographic data. Simply include <code>geometry = TRUE</code> in functions like <code>get_acs()</code> to pull the shapes data as <code>sf</code>. The <code>state</code> and <code>county</code> arguments accept names and FIPS codes.</p>
<p><code>library(tidycensus)</code> sometimes requires the same Census API Key we used in the API tutorial (<a href="https://api.census.gov/data/key_signup.html">sign up here</a>). You should be able to install your API key into your version of R with <code>census_api_key("your-key-string", install = TRUE)</code>. To obtain your keystring, you can use <code>library(dotenv)</code> and <code>Sys.getenv(&lt;key name in .env file&gt;)</code>.</p>
<p><code>library(tidycensus)</code> has two big differences from <code>library(tigris)</code>: 1. it can pull Census data with the geographic data, and 2. it only provides cartographic boundary files that are smaller and quicker to load and more familiar than TIGER/Line shapefiles by default.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb22"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1"></a><span class="fu">library</span>(tidycensus)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: package 'tidycensus' was built under R version 4.3.3</code></pre>
</div>
<div class="sourceCode cell-code" id="cb24"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb24-1"><a href="#cb24-1"></a>dc_income <span class="ot">&lt;-</span> <span class="fu">get_acs</span>(</span>
<span id="cb24-2"><a href="#cb24-2"></a>  <span class="at">geography =</span> <span class="st">"tract"</span>, </span>
<span id="cb24-3"><a href="#cb24-3"></a>  <span class="at">variables =</span> <span class="st">"B19013_001"</span>, </span>
<span id="cb24-4"><a href="#cb24-4"></a>  <span class="at">state =</span> <span class="st">"DC"</span>, </span>
<span id="cb24-5"><a href="#cb24-5"></a>  <span class="at">county =</span> <span class="st">"District of Columbia"</span>, </span>
<span id="cb24-6"><a href="#cb24-6"></a>  <span class="at">geometry =</span> <span class="cn">TRUE</span>,</span>
<span id="cb24-7"><a href="#cb24-7"></a>  <span class="at">year =</span> <span class="dv">2019</span>,</span>
<span id="cb24-8"><a href="#cb24-8"></a>  <span class="at">progress =</span> <span class="cn">FALSE</span></span>
<span id="cb24-9"><a href="#cb24-9"></a>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Getting data from the 2015-2019 5-year ACS</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Downloading feature geometry from the Census website.  To cache shapefiles for use in future sessions, set `options(tigris_use_cache = TRUE)`.</code></pre>
</div>
</div>
<p>Both <code>library(tigris)</code> and <code>library(tidycensus)</code> have a <code>year</code> parameter that determines the year of the data obtained in functions like <code>tidycensus::get_acs()</code> or <code>tigris::states()</code>. This parameter currently defaults to 2020 for <code>get_acs()</code> and <code>tigris</code> functions. <code>tidycensus::get_acs()</code> also notably defaults to pulling 5-year ACS data. We recommend reading the documentation for these functions to understand the parameter options and their default values.</p>
</section>
</section>
<section id="choropleths" class="level2" data-number="23.5">
<h2 data-number="23.5" class="anchored" data-anchor-id="choropleths"><span class="header-section-number">23.5</span> Choropleths</h2>
<p>Choropleths are maps that use fill to display the variation in a variable across geographies.</p>
<div class="cell">
<div class="cell-output cell-output-stderr">
<pre><code>Getting data from the 2018-2022 5-year ACS</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Downloading feature geometry from the Census website.  To cache shapefiles for use in future sessions, set `options(tigris_use_cache = TRUE)`.</code></pre>
</div>
<div class="cell-output-display">
<p><img src="30_geospatial_files/figure-html/unnamed-chunk-16-1.png" class="img-fluid" width="480"></p>
</div>
</div>
<div class="callout callout-style-simple callout-none no-icon callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span style="color:#1696d2;">Exercise 3</span>
</div>
</div>
<div class="callout-body-container callout-body">
<ol type="1">
<li>Copy the code that pulls income in DC by census tract under <code>library(tidycensus)</code>.</li>
<li>Try to recreate the above choropleth using <code>fill</code>.</li>
<li><strong>Hint:</strong> Use <code>scale_fill_gradient()</code> with <code>low = "#cfe8f3"</code> and <code>high = "#062635"</code>.</li>
</ol>
</div>
</div>
</section>
<section id="spatial-concepts" class="level2" data-number="23.6">
<h2 data-number="23.6" class="anchored" data-anchor-id="spatial-concepts"><span class="header-section-number">23.6</span> Spatial concepts</h2>
<p>Geospatial work requires making an assumption about the shape of the Earth and a decision about how to project three-dimensions on to a two-dimensional surface.</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Note
</div>
</div>
<div class="callout-body-container callout-body">
<p>The Earth is an ellipsoid where the diameter from pole-to-pole is smaller than from equator to equator. In other words, it is swollen at the equator.</p>
</div>
</div>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Geographic coordinate reference systems
</div>
</div>
<div class="callout-body-container callout-body">
<p>Geographic coordinate reference systems represent geographies with a three-dimensional representation of the Earth. (i.e., The data have not been projected from what we think of as a globe to what we think of as a map). Data are typically stored as longitude and latitude.</p>
</div>
</div>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Projected coordinate reference system
</div>
</div>
<div class="callout-body-container callout-body">
<p>Projected coordinate reference system represent geographies with a two-dimensional representation of the Earth. A projected CRS is the combination of a geographic CRS and a projection. Data are typically stored in feet or meters, which is useful for distance-based spatial operations like calculating distances and creating buffers.</p>
</div>
</div>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Projection
</div>
</div>
<div class="callout-body-container callout-body">
<p>A projection is a mathematical transformation that converts three-dimensional coordinates for a spheroid/ellipsoid into a two-dimensions.</p>
</div>
</div>
<section id="popular-projections" class="level3" data-number="23.6.1">
<h3 data-number="23.6.1" class="anchored" data-anchor-id="popular-projections"><span class="header-section-number">23.6.1</span> Popular projections</h3>
<p>All projections are wrong, but all projections are wrong in different ways with different uses.</p>
<p>Cylindrical projections maintain lines of longitude and latitude but distort areas and distances. Conic projections distort longitudes and latitudes but maintain areas. Azimuthal projections maintain distances but struggle to project large areas.</p>
<section id="mercator-projection" class="level4">
<h4 class="anchored" data-anchor-id="mercator-projection">Mercator projection</h4>
<p>The Mercator projection is widespread because it maintains straight lines for longitude and latitude. This was useful for navigators on the open sea hundreds of years ago. This is less useful in the 21st century. The Mercator projection is conformal, so while it maintains angles, it seriously distorts area. To see this, play the <a href="https://bramus.github.io/mercator-puzzle-redux/">Mercator Puzzle</a>.</p>
<div id="fig-mercator" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="images/mercator.png" class="img-fluid figure-img" style="width:70.0%"></p>
<figcaption class="figure-caption">Figure&nbsp;23.1: Mercator</figcaption>
</figure>
</div>
<p>Source: <a href="https://www.britannica.com/science/Mercator-projection#/media/1/375638/231099">Encyclopædia Britannica</a></p>
</section>
<section id="albers-equal-area-projection" class="level4">
<h4 class="anchored" data-anchor-id="albers-equal-area-projection">Albers Equal Area Projection</h4>
<p>The Albers Equal Area projection, which is a conic projection, doesn’t maintain angles, but it is an equal area projection. It is the default projection of the Urban Institute.</p>
<div id="fig-albers" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="images/albers.png" class="img-fluid figure-img" style="width:70.0%"></p>
<figcaption class="figure-caption">Figure&nbsp;23.2: Albers</figcaption>
</figure>
</div>
</section>
<section id="state-plane-coordinate-systems-spcs" class="level4">
<h4 class="anchored" data-anchor-id="state-plane-coordinate-systems-spcs">State Plane Coordinate Systems (SPCS)</h4>
<p>The State Plane Coordinate System is a collection of 124 coordinate systems for specific areas of the United States. States with east-west directions, like Tennessee use the Lambert conformal conic projection. North-south states like Illinois use the transverse Mercator projection. SPCS is not a projection, but the coordinate systems are projected. <a href="https://desktop.arcgis.com/en/arcmap/10.3/guide-books/map-projections/state-plane-coordinate-system.htm">This site</a> has a thorough introduction.</p>
<div id="fig-state-planes" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="images/spcs83.png" class="img-fluid figure-img" style="width:70.0%"></p>
<figcaption class="figure-caption">Figure&nbsp;23.3: State Planes</figcaption>
</figure>
</div>
<p>Source: <a href="https://geodesy.noaa.gov/SPCS/maps.shtml">NOAA</a></p>
</section>
<section id="epsg-codes" class="level4">
<h4 class="anchored" data-anchor-id="epsg-codes">EPSG Codes</h4>
<p>A CRS can be uniquely identified by EPSG codes and proj4 strings. EPSG comes from the European Petrol Survey Group, which no longer exists. EPSG codes are 4-6 numbers. Always check to see if a CRS is specified after loading spatial data. Here are some defaults:</p>
<ul>
<li>The EPSG code will always be 4326 for GeoJSONs.</li>
<li>.csv files with longitude and latitude will typically be 4326.</li>
<li>R should read the CRS from <code>.prj</code> file when reading shapefiles. If it fails, open the <code>.prj</code> file and use <a href="http://prj2epsg.org">this tool</a> to identify the EPSG code.</li>
</ul>
<p>Use <code>st_crs()</code> to see the CRS. Use <code>st_set_crs()</code> to set the CRS. Use <code>st_transform()</code> to transform the CRS. Note that <code>st_set_crs()</code> simply adds or updates CRS information - it does not transform the data. When using multiple different geospatial datasets for mapping (e.g.&nbsp;layering points and polygons), they should have the same CRS prior to mapping.</p>
<p><a href="epsg.io">epsg.io</a> and <a href="spatialreference.org">spatialreference.org</a> are useful for finding and learning more about EPSG codes.</p>
</section>
<section id="datum" class="level4">
<h4 class="anchored" data-anchor-id="datum">Datum</h4>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Datum
</div>
</div>
<div class="callout-body-container callout-body">
<p>A datum is a reference point for measuring locations on the surface of the Earth. The datum defines an anchor point for coordinate systems and thus allows a unique set of longitudes and latitudes to fully define the surface of the Earth.</p>
</div>
</div>
<p>The invention of GPS has standardized datums. Geodetic datums like the North American Datum of 1983 (<strong>NAD83</strong>) and the World Geodetic System of 1984 (<strong>WGS84</strong>) now dominate. In fact, all GPS measurements are based on WGS84. This <a href="https://www.esri.com/news/arcuser/0401/datum.html">blog</a> describes the importance of datums.</p>
</section>
<section id="librarycrsuggest" class="level4">
<h4 class="anchored" data-anchor-id="librarycrsuggest"><code>library(crsuggest)</code></h4>
<p><a href="https://github.com/walkerke/crsuggest"><code>library(crsuggest)</code></a> can simplify the process of picking a CRS.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb29"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb29-1"><a href="#cb29-1"></a><span class="fu">library</span>(crsuggest)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Using the EPSG Dataset v10.019, a product of the International Association of Oil &amp; Gas Producers. 
Please view the terms of use at https://epsg.org/terms-of-use.html.</code></pre>
</div>
<div class="sourceCode cell-code" id="cb31"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb31-1"><a href="#cb31-1"></a><span class="fu">suggest_crs</span>(amtrak_stations)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 10 × 6
   crs_code crs_name                        crs_type crs_gcs crs_units crs_proj4
   &lt;chr&gt;    &lt;chr&gt;                           &lt;chr&gt;      &lt;dbl&gt; &lt;chr&gt;     &lt;chr&gt;    
 1 6350     NAD83(2011) / Conus Albers      project…    6318 m         +proj=ae…
 2 5072     NAD83(NSRS2007) / Conus Albers  project…    4759 m         +proj=ae…
 3 5071     NAD83(HARN) / Conus Albers      project…    4152 m         +proj=ae…
 4 5070     NAD83 / Conus Albers            project…    4269 m         +proj=ae…
 5 5069     NAD27 / Conus Albers            project…    4267 m         +proj=ae…
 6 6925     NAD83(2011) / Kansas LCC (ftUS) project…    6318 us-ft     +proj=lc…
 7 6924     NAD83(2011) / Kansas LCC        project…    6318 m         +proj=lc…
 8 6923     NAD83 / Kansas LCC (ftUS)       project…    4269 us-ft     +proj=lc…
 9 6922     NAD83 / Kansas LCC              project…    4269 m         +proj=lc…
10 6467     NAD83(2011) / Kansas North (ft… project…    6318 us-ft     +proj=lc…</code></pre>
</div>
<div class="sourceCode cell-code" id="cb33"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb33-1"><a href="#cb33-1"></a>virginia_stations <span class="ot">&lt;-</span> amtrak_stations <span class="sc">|&gt;</span></span>
<span id="cb33-2"><a href="#cb33-2"></a>  <span class="fu">filter</span>(state <span class="sc">==</span> <span class="st">"VA"</span>)</span>
<span id="cb33-3"><a href="#cb33-3"></a></span>
<span id="cb33-4"><a href="#cb33-4"></a><span class="fu">suggest_crs</span>(virginia_stations)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 10 × 6
   crs_code crs_name                        crs_type crs_gcs crs_units crs_proj4
   &lt;chr&gt;    &lt;chr&gt;                           &lt;chr&gt;      &lt;dbl&gt; &lt;chr&gt;     &lt;chr&gt;    
 1 6593     NAD83(2011) / Virginia North (… project…    6318 us-ft     +proj=lc…
 2 6592     NAD83(2011) / Virginia North    project…    6318 m         +proj=lc…
 3 3686     NAD83(NSRS2007) / Virginia Nor… project…    4759 us-ft     +proj=lc…
 4 3685     NAD83(NSRS2007) / Virginia Nor… project…    4759 m         +proj=lc…
 5 32146    NAD83 / Virginia North          project…    4269 m         +proj=lc…
 6 32046    NAD27 / Virginia North          project…    4267 us-ft     +proj=lc…
 7 2924     NAD83(HARN) / Virginia North (… project…    4152 us-ft     +proj=lc…
 8 2853     NAD83(HARN) / Virginia North    project…    4152 m         +proj=lc…
 9 2283     NAD83 / Virginia North (ftUS)   project…    4269 us-ft     +proj=lc…
10 6488     NAD83(2011) / Maryland (ftUS)   project…    6318 us-ft     +proj=lc…</code></pre>
</div>
</div>
<p>The top suggestion for <code>virginia_stations</code> is <code>CRS == 6593</code>. If we <a href="http://epsg.io/6593">look up</a> this CRS we see it has geodetic datum NAD83 and is based on the Lambert Conformal Conic projection used for SPCS. If we <a href="https://www.spatialreference.org/ref/?search=virginia&amp;srtext=Search">look up</a> the best SPCS for Northern Virginia, we get <code>CRS == 3686</code>, which is the third recommendation.</p>
<p>The differences between these two recommendations are not significant.</p>
</section>
<section id="bottom-line" class="level4">
<h4 class="anchored" data-anchor-id="bottom-line">Bottom line</h4>
<p>That’s a lot of technical information. When mapping in the US</p>
<ol type="1">
<li>Use <code>CRS = 4326</code> when you load the data to understand the locations you are mapping. <em>This is not a projection</em> but plotting the data acts like a projection.</li>
<li>Use <code>CRS = 5070</code> if you are mapping the entire Continental US. Other useful EPSG codes are available <a href="https://guides.library.duke.edu/r-geospatial/CRS">here</a>.</li>
<li>Use the recommended state plane coordinate system for state and local maps.</li>
</ol>
<p>Here’s the map from earlier with EPSG 4326 on the left and EPSG 5070 (Alber’s Equal Area Conic Projection) on the right:</p>
<div class="cell">
<div class="cell-output-display">
<p><img src="30_geospatial_files/figure-html/unnamed-chunk-19-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<div class="callout callout-style-simple callout-none no-icon callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span style="color:#1696d2;">Exercise 4</span>
</div>
</div>
<div class="callout-body-container callout-body">
<ol type="1">
<li>Copy-and-paste the AidData exercise from exercise 2.</li>
<li>Repeat the mapping with a EPSG code that makes sense for Bangladesh using <code>st_transform()</code> (<strong>Hint:</strong> you can identify the EPSG code using <code>suggest_crs(aiddata)</code>).</li>
<li>Copy-and-paste the AidData exercise from exercise 2 again.</li>
<li>Repeat the mapping with a EPSG code that makes sense for Bangladesh using <code>coord_sf(crs = ####)</code> where <code>####</code> is the EPSG code from step 2 (<strong>Hint:</strong> <code>coord_sf()</code> can be added to your mapping code following a + ). This skips the need for <code>st_transform()</code> when making maps.</li>
</ol>
</div>
</div>
</section>
</section>
</section>
<section id="spatial-operations" class="level2" data-number="23.7">
<h2 data-number="23.7" class="anchored" data-anchor-id="spatial-operations"><span class="header-section-number">23.7</span> Spatial operations</h2>
<p>We often want to manipulate spatial data or use spatial data for calculations. This section covers a few common operations.</p>
<section id="aggregation" class="level3" data-number="23.7.1">
<h3 data-number="23.7.1" class="anchored" data-anchor-id="aggregation"><span class="header-section-number">23.7.1</span> Aggregation</h3>
<p>Sometimes we want to aggregate smaller geographies into larger geographies. This is simple with a <code>group_by()</code> and <code>summarize()</code> workflow. Suppose we want to combine North Dakota and South Dakota into Dakota.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb35"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb35-1"><a href="#cb35-1"></a><span class="co"># states to combine</span></span>
<span id="cb35-2"><a href="#cb35-2"></a>dmv_names <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">"South Dakota"</span>, <span class="st">"North Dakota"</span>)</span>
<span id="cb35-3"><a href="#cb35-3"></a></span>
<span id="cb35-4"><a href="#cb35-4"></a><span class="co"># add a projection</span></span>
<span id="cb35-5"><a href="#cb35-5"></a>states <span class="ot">&lt;-</span> states <span class="sc">|&gt;</span></span>
<span id="cb35-6"><a href="#cb35-6"></a>  <span class="fu">st_transform</span>(<span class="at">crs =</span> <span class="dv">5070</span>)</span>
<span id="cb35-7"><a href="#cb35-7"></a></span>
<span id="cb35-8"><a href="#cb35-8"></a><span class="co"># aggregate states and make a map</span></span>
<span id="cb35-9"><a href="#cb35-9"></a>states <span class="sc">|&gt;</span></span>
<span id="cb35-10"><a href="#cb35-10"></a>  <span class="fu">mutate</span>(<span class="at">new_NAME =</span> <span class="fu">if_else</span>(NAME <span class="sc">%in%</span> dmv_names, <span class="st">"Dakota"</span>, NAME)) <span class="sc">|&gt;</span></span>
<span id="cb35-11"><a href="#cb35-11"></a>  <span class="fu">group_by</span>(new_NAME) <span class="sc">|&gt;</span></span>
<span id="cb35-12"><a href="#cb35-12"></a>  <span class="fu">summarize</span>() <span class="sc">|&gt;</span></span>
<span id="cb35-13"><a href="#cb35-13"></a>  <span class="fu">ggplot</span>() <span class="sc">+</span></span>
<span id="cb35-14"><a href="#cb35-14"></a>  <span class="fu">geom_sf</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="30_geospatial_files/figure-html/unnamed-chunk-22-1.png" class="img-fluid" width="672"></p>
</div>
</div>
</section>
<section id="spatial-joins" class="level3" data-number="23.7.2">
<h3 data-number="23.7.2" class="anchored" data-anchor-id="spatial-joins"><span class="header-section-number">23.7.2</span> Spatial Joins</h3>
<p>Spatial joins are joins like <code>left_join()</code> but the join is based on geography instead of “by” variables. <strong>Note:</strong> both geographies must have the same CRS. Like with any join, it is important to track the number of rows before and after joins and to note that joins may be one-to-one, one-to-many.</p>
<p><code>st_join()</code> performs a left spatial join in R. <code>st_intersects</code> means observations will join if the geographies in <code>x</code> touch the geographies in <code>y</code>. The <code>sf</code> package offers a number of different geometric confirmations that can be used for spatial joins, such as <code>st_covered_by</code> (identifies if <code>x</code> is copletely within <code>y</code>), <code>st_within</code> (identifies if <code>x</code> is within a specified distance of <code>y</code>) and many more. The <a href="https://github.com/rstudio/cheatsheets/blob/main/sf.pdf">sf cheat sheet</a> provides a good outline of the different options.</p>
<p>Suppose we want to count the number of Amtrak stations in each state.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb36"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb36-1"><a href="#cb36-1"></a><span class="co"># set states CRS to 4326 to match the Amtrak data</span></span>
<span id="cb36-2"><a href="#cb36-2"></a>amtrak_stations <span class="ot">&lt;-</span> <span class="fu">st_transform</span>(amtrak_stations, <span class="at">crs =</span> <span class="dv">5070</span>)</span>
<span id="cb36-3"><a href="#cb36-3"></a></span>
<span id="cb36-4"><a href="#cb36-4"></a><span class="co"># dimension before join</span></span>
<span id="cb36-5"><a href="#cb36-5"></a><span class="fu">dim</span>(amtrak_stations)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 1096   12</code></pre>
</div>
<div class="sourceCode cell-code" id="cb38"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb38-1"><a href="#cb38-1"></a><span class="co"># spatial join using intersection</span></span>
<span id="cb38-2"><a href="#cb38-2"></a>amtrak <span class="ot">&lt;-</span> <span class="fu">st_join</span>(states, amtrak_stations, <span class="at">join =</span> st_intersects)</span>
<span id="cb38-3"><a href="#cb38-3"></a></span>
<span id="cb38-4"><a href="#cb38-4"></a><span class="co"># dimension after join -- lose international stations</span></span>
<span id="cb38-5"><a href="#cb38-5"></a><span class="fu">dim</span>(amtrak)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 1080   21</code></pre>
</div>
<div class="sourceCode cell-code" id="cb40"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb40-1"><a href="#cb40-1"></a><span class="co"># count the number of stations per state</span></span>
<span id="cb40-2"><a href="#cb40-2"></a>amtrak <span class="sc">|&gt;</span></span>
<span id="cb40-3"><a href="#cb40-3"></a>  <span class="fu">as_tibble</span>() <span class="sc">|&gt;</span> <span class="co"># converting from sf to tibble speeds calculations</span></span>
<span id="cb40-4"><a href="#cb40-4"></a>  <span class="fu">group_by</span>(NAME) <span class="sc">|&gt;</span></span>
<span id="cb40-5"><a href="#cb40-5"></a>  <span class="fu">summarize</span>(<span class="at">number_of_stations =</span> <span class="fu">n</span>()) <span class="sc">|&gt;</span></span>
<span id="cb40-6"><a href="#cb40-6"></a>  <span class="fu">arrange</span>(<span class="fu">desc</span>(number_of_stations))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 49 × 2
   NAME         number_of_stations
   &lt;chr&gt;                     &lt;int&gt;
 1 California                  184
 2 Oregon                       87
 3 New York                     80
 4 Pennsylvania                 63
 5 Michigan                     54
 6 Washington                   50
 7 Illinois                     41
 8 Wisconsin                    37
 9 Florida                      31
10 Texas                        31
# ℹ 39 more rows</code></pre>
</div>
</div>
</section>
<section id="buffers" class="level3" data-number="23.7.3">
<h3 data-number="23.7.3" class="anchored" data-anchor-id="buffers"><span class="header-section-number">23.7.3</span> Buffers</h3>
<p>Adding buffers to points, lines, and polygons is useful for counting shapes near other shapes. For instance, we may want to count the number of housing units within 500 meters of a metro station or the number of schools more than 5 miles from a fire station.</p>
<p>Suppose we want to count the number of Amtrak stations within 5 kilometers of each Amtrak station. We can buffer the Amtrak station points, join the unbuffered data to the buffered data, and then count.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb42"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb42-1"><a href="#cb42-1"></a><span class="co"># add a buffer of 5 kilometers to each station</span></span>
<span id="cb42-2"><a href="#cb42-2"></a><span class="co"># the units package is useful for setting buffers with different units</span></span>
<span id="cb42-3"><a href="#cb42-3"></a>amtrak_stations_buffered <span class="ot">&lt;-</span> <span class="fu">st_buffer</span>(</span>
<span id="cb42-4"><a href="#cb42-4"></a>  amtrak_stations, </span>
<span id="cb42-5"><a href="#cb42-5"></a>  <span class="at">dist =</span> units<span class="sc">::</span><span class="fu">set_units</span>(<span class="dv">5</span>, <span class="st">"km"</span>)</span>
<span id="cb42-6"><a href="#cb42-6"></a>)</span>
<span id="cb42-7"><a href="#cb42-7"></a></span>
<span id="cb42-8"><a href="#cb42-8"></a><span class="co"># spatial join the unbuffered shapes to the buffer shapes</span></span>
<span id="cb42-9"><a href="#cb42-9"></a>amtrak_stations_joined <span class="ot">&lt;-</span> <span class="fu">st_join</span>(</span>
<span id="cb42-10"><a href="#cb42-10"></a>  amtrak_stations_buffered,</span>
<span id="cb42-11"><a href="#cb42-11"></a>  amtrak_stations, </span>
<span id="cb42-12"><a href="#cb42-12"></a>  <span class="at">join =</span> st_intersects</span>
<span id="cb42-13"><a href="#cb42-13"></a>)</span>
<span id="cb42-14"><a href="#cb42-14"></a></span>
<span id="cb42-15"><a href="#cb42-15"></a><span class="co"># count the station names</span></span>
<span id="cb42-16"><a href="#cb42-16"></a>amtrak_stations_joined <span class="sc">|&gt;</span></span>
<span id="cb42-17"><a href="#cb42-17"></a>  <span class="fu">as_tibble</span>() <span class="sc">|&gt;</span></span>
<span id="cb42-18"><a href="#cb42-18"></a>  <span class="fu">count</span>(stationnam.x, <span class="at">sort =</span> <span class="cn">TRUE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 1,007 × 2
   stationnam.x                   n
   &lt;chr&gt;                      &lt;int&gt;
 1 Monterey, CA                  27
 2 Yosemite National Park, CA    17
 3 Boston, MA                     9
 4 Salem, OR                      9
 5 Seaside, OR                    8
 6 Manchester Center, VT          6
 7 Eugene, OR                     5
 8 Las Vegas, NV                  5
 9 Oakland, CA                    5
10 Palm Springs, CA               5
# ℹ 997 more rows</code></pre>
</div>
</div>
</section>
<section id="distances" class="level3" data-number="23.7.4">
<h3 data-number="23.7.4" class="anchored" data-anchor-id="distances"><span class="header-section-number">23.7.4</span> Distances</h3>
<p>Euclidean distance is common for calculating straight line distances but does not make sense for calculating distances on the surface of an ellipsoid like Earth.</p>
<p><span class="math display">\[d(\vec{p}, \vec{q}) = \sqrt{\sum_{i = 1}^n(q_i - p_i)^2}\]</span></p>
<p>Instead, it is common to use Haversine distance which accounts for the curvature in the globe.</p>
<div id="fig-haversine" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="images/haversine.png" class="img-fluid figure-img" style="width:70.0%"></p>
<figcaption class="figure-caption">Figure&nbsp;23.4: Haversine Distance</figcaption>
</figure>
</div>
<p>Suppose we want to find the closest and furthest Amtrak stations from Washington DC’s Union Station.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb44"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb44-1"><a href="#cb44-1"></a><span class="co"># create a data frame with just Union Station</span></span>
<span id="cb44-2"><a href="#cb44-2"></a>union_station <span class="ot">&lt;-</span> amtrak_stations <span class="sc">|&gt;</span></span>
<span id="cb44-3"><a href="#cb44-3"></a>  <span class="fu">filter</span>(state <span class="sc">==</span> <span class="st">"DC"</span>)</span>
<span id="cb44-4"><a href="#cb44-4"></a></span>
<span id="cb44-5"><a href="#cb44-5"></a>no_union_station <span class="ot">&lt;-</span> amtrak_stations <span class="sc">|&gt;</span></span>
<span id="cb44-6"><a href="#cb44-6"></a>  <span class="fu">filter</span>(state <span class="sc">!=</span> <span class="st">"DC"</span>) </span>
<span id="cb44-7"><a href="#cb44-7"></a></span>
<span id="cb44-8"><a href="#cb44-8"></a><span class="co"># calculate the distance from Union Station to all other stations</span></span>
<span id="cb44-9"><a href="#cb44-9"></a>amtrak_distances <span class="ot">&lt;-</span> <span class="fu">st_distance</span>(union_station, no_union_station)</span>
<span id="cb44-10"><a href="#cb44-10"></a></span>
<span id="cb44-11"><a href="#cb44-11"></a><span class="co"># find the closest station</span></span>
<span id="cb44-12"><a href="#cb44-12"></a>amtrak_stations <span class="sc">|&gt;</span></span>
<span id="cb44-13"><a href="#cb44-13"></a>  <span class="fu">slice</span>(<span class="fu">which.min</span>(amtrak_distances)) <span class="sc">|&gt;</span></span>
<span id="cb44-14"><a href="#cb44-14"></a>  <span class="fu">select</span>(stationnam, city)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Simple feature collection with 1 feature and 2 fields
Geometry type: POINT
Dimension:     XY
Bounding box:  xmin: 1618448 ymin: 1915016 xmax: 1618448 ymax: 1915016
Projected CRS: NAD83 / Conus Albers
      stationnam       city                geometry
1 Alexandria, VA Alexandria POINT (1618448 1915016)</code></pre>
</div>
<div class="sourceCode cell-code" id="cb46"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb46-1"><a href="#cb46-1"></a><span class="co"># find the further station</span></span>
<span id="cb46-2"><a href="#cb46-2"></a>amtrak_stations <span class="sc">|&gt;</span></span>
<span id="cb46-3"><a href="#cb46-3"></a>  <span class="fu">slice</span>(<span class="fu">which.max</span>(amtrak_distances)) <span class="sc">|&gt;</span></span>
<span id="cb46-4"><a href="#cb46-4"></a>  <span class="fu">select</span>(stationnam, city)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Simple feature collection with 1 feature and 2 fields
Geometry type: POINT
Dimension:     XY
Bounding box:  xmin: -2328052 ymin: 2299661 xmax: -2328052 ymax: 2299661
Projected CRS: NAD83 / Conus Albers
   stationnam    city                 geometry
1 Fortuna, CA Fortuna POINT (-2328052 2299661)</code></pre>
</div>
</div>
</section>
</section>
<section id="geospatial-modeling" class="level2" data-number="23.8">
<h2 data-number="23.8" class="anchored" data-anchor-id="geospatial-modeling"><span class="header-section-number">23.8</span> Geospatial modeling</h2>
<p>Cross-sectional regression models assume that the error term is independently and identically distributed, which in turn means the dependent variable is independently and identically distributed. This is often a reasonable assumption.</p>
<p>The assumption of independence often falls apart with spatial data. If number of coal power plants in a state is an independent variable and atmospheric carbon dioxide in a state is the dependent variable, then it doesn’t make much sense to assume that North Carolina and South Carolina are independent. If South Carolina has many coal burning power plants, then the emissions could affect atmospheric carbon dioxide in North Carolina.</p>
<p>Spatial regression methods attempt to account for this dependence between observations.</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Spatial autocorrelation
</div>
</div>
<div class="callout-body-container callout-body">
<p><strong>Spatial autocorrelation:</strong> Correlation between observations that are geographically close.</p>
</div>
</div>
<p>Process:</p>
<ol type="1">
<li>Estimate a non-spatial regression model.</li>
<li>Use tests of spatial autocorrelation like Moran’s I, Geary’s c, or Getis and Ord’s G-statistic on the residuals to test for spatial autocorrelation.</li>
<li>If spatial autocorrelation exists, the use a spatial error model or a spatial lag model.</li>
</ol>
</section>
<section id="parting-thoughts" class="level2" data-number="23.9">
<h2 data-number="23.9" class="anchored" data-anchor-id="parting-thoughts"><span class="header-section-number">23.9</span> Parting Thoughts</h2>
<p>This note set works entirely with vector spatial data. Vector data consists of vertices turned into points, lines, and polygons.</p>
<p>Some spatial data are raster data, which are stored as pixels or grid cells. For example, a raster data set could have an even one square mile grid over the entire United States with data about the amount of soy crops within each pixel. It is common for satellite data to be converted to rasters. <a href="https://datacarpentry.org/organization-geospatial/01-intro-raster-data/">This website contains good example of raster data.</a></p>
<p>This is a brief introduction to spatial data handling in R. If you are interested in further understanding spatial data handling, processing, visualization, and modeling, we recommend <em>Geocomputation with R</em> <span class="citation" data-cites="geocomp">(<a href="references.html#ref-geocomp" role="doc-biblioref"><strong>geocomp?</strong></a>)</span>. <a href="https://r-spatial.org/book/">Spatial Data Science</a> provides a great discussion of statistical modeling but is more technical and mathematical (also written in R). <a href="https://geographicdata.science/book/intro.html">Geographical Data Science</a> is also a fantastic place to learn more, but note that it is written in Python.</p>
</section>
<section id="more-resources" class="level2" data-number="23.10">
<h2 data-number="23.10" class="anchored" data-anchor-id="more-resources"><span class="header-section-number">23.10</span> More Resources</h2>
<ul>
<li><a href="https://r.geocompx.org">Geocomputation with R</a></li>
<li><a href="https://r-spatial.org/book/">Spatial Data Science</a></li>
<li><a href="https://geographicdata.science/book/intro.html">Geographical Data Science</a></li>
<li><a href="https://www.r-spatial.org/r/2018/10/25/ggplot2-sf.html">Drawing Beautiful Maps with sf - part 1</a></li>
<li><a href="https://www.r-spatial.org/r/2018/10/25/ggplot2-sf-2.html">Drawing Beautiful Maps with sf - part 2</a></li>
<li><a href="https://spatialanalysis.github.io/workshop-notes/">R Spatial Workshop Notes</a></li>
<li><a href="https://walker-data.com/census-r/mapping-census-data-with-r.html">Analyzing US Census Data by Kyle Walker – Chapter 6</a></li>
<li><a href="https://github.com/rstudio/cheatsheets/blob/main/sf.pdf">sf Cheat Sheet</a></li>
</ul>


</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="./27_advanced-unsupervised-ml.html" class="pagination-link">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">22</span>&nbsp; <span class="chapter-title">Mixture Distributions and Mixture Modeling</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="./28_text-analysis.html" class="pagination-link">
        <span class="nav-page-text"><span class="chapter-number">24</span>&nbsp; <span class="chapter-title">Text Analysis</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->



</body></html>